# fly.toml app configuration file generated for almanac-twilight-sun-3962 on 2025-08-06T21:49:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'almanac-photography'
primary_region = 'iad'

[build]

[mounts]
source = 'almanac_data'
destination = '/app/instance'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
max_machines = 1

[[services]]
processes = ['app']

[[vm]]
memory = '1gb'
memory_mb = 1024
cpu_kind = 'shared'
cpus = 1
